swagger: '2.0'
info:
  title: Test Microservice API
  version: 1.0.0
  description: Test API matching company file structure
host: localhost:3000/api
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      summary: Get Users
      description: Get Users
      tags:
        - app
      parameters:
        - name: page
          in: query
          required: false
          type: string
          description: page query parameter
        - name: limit
          in: query
          required: false
          type: string
          description: limit query parameter
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      summary: Create User
      description: Create User
      tags:
        - app
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: name field
              email:
                type: string
                description: email field
              role:
                type: string
                description: role field
            required:
              - name
              - email
          description: Request body
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /users/:id:
    get:
      summary: Get User By Id
      description: Get User By Id
      tags:
        - app
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: id path parameter
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    put:
      summary: Update User
      description: Update User
      tags:
        - app
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: id path parameter
        - name: body
          in: body
          required: true
          schema:
            type: object
          description: Request body
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /app/user:
    delete:
      summary: Delete User
      description: Delete User
      tags:
        - app
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: id path parameter
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /orders:
    get:
      summary: Get Orders
      description: Get Orders
      tags:
        - app
      parameters:
        - name: userId
          in: query
          required: true
          type: string
          description: userId query parameter
        - name: status
          in: query
          required: true
          type: string
          description: status query parameter
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      summary: Create Order
      description: Create Order
      tags:
        - app
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              userId:
                type: string
                description: userId field
              items:
                type: string
                description: items field
              total:
                type: string
                description: total field
            required:
              - userId
              - items
              - total
          description: Request body
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /orders/:id:
    get:
      summary: Get Order By Id
      description: Get Order By Id
      tags:
        - app
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: id path parameter
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    delete:
      summary: Cancel Order
      description: Cancel Order
      tags:
        - app
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: id path parameter
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /invoice:
    post:
      summary: Create Invoice
      description: Create Invoice
      tags:
        - app
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              amount:
                type: string
                description: amount field
              currency:
                type: string
                description: currency field
              orderId:
                type: string
                description: orderId field
            required:
              - amount
              - currency
              - orderId
          description: Request body
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /invoice/:invoiceId:
    get:
      summary: Get Invoice Status
      description: Get Invoice Status
      tags:
        - app
      parameters:
        - name: invoiceId
          in: path
          required: true
          type: string
          description: invoiceId path parameter
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /webhook/btcpay:
    post:
      summary: Handle Webhook
      description: Handle Webhook
      tags:
        - app
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
definitions: {}
